Add some information on the docker --workdir option
carpentries-incubator/singularity-introduction pull request #25
Opened 2021-08-18 11:35 UTC by jcohen02

This PR aims to address issue #24 by adding a callout box to the end of episode 6 ([06-singularity-images-prep.md](https://github.com/carpentries-incubator/singularity-introduction/blob/gh-pages/_episodes/06-singularity-images-prep.md)) describing how the `--workdir` or `-w` Docker command line option can help to simplify `singularity` command lines when using the Docker Singularity container (and especially when using an alias to run the container).

I'd appreciate some feedback from the reviewers on whether the new text is sufficiently clear - this concept was a little challenging to explain clearly so any suggestions on how the text might be improved are welcome.

2021-08-27 20:19 UTC, sstevens2 commented on _episodes/06-singularity-images-prep.md
> +> We saw that we bind mount the current working directory on our host system into each instance of the Docker Singularity container that we start. We can then access the files within this directory w
```suggestion
> We saw that we bind mount the current working directory on our 
> host system into each instance of the Docker Singularity container 
> that we start. We can then access the files within this directory 
> when inside the container. 
> We can also write output to this location inside the container 
> and then have access to the output files on our host system 
> after the container has exited.
```
splitting lines

2021-08-27 20:20 UTC, sstevens2 commented on _episodes/06-singularity-images-prep.md
> +> Since we bind mount our current working directory `${PWD}` to the location `/home/singularity` within the container, all files from the current directory on our host system that we reference when w
```suggestion
> Since we bind mount our current working directory `${PWD}` to 
> the location `/home/singularity` within the container, all files from the 
> current directory on our host system that we reference when we're 
> inside the container appear at the location `/home/singularity`.
```
splitting lines

2021-08-27 20:21 UTC, sstevens2 commented on _episodes/06-singularity-images-prep.md
> +> When we provide file arguments to the `singularity` command, we therefore need to provide the full path to these files _within_ the running container. This means that the files are located in the `
```suggestion
> When we provide file arguments to the `singularity` command, 
> we therefore need to provide the full path to these files _within_ 
> the running container. This means that the files are located in the 
> `/home/singularity` directory. To avoid having to provide the full 
> path to each file, we can using Docker's `--workdir` or `-w` option 
> to set the default working directory within the container to `/home/singularity`. 
> We then no longer need to prefix file names with their full path location (`/home/singularity/)` 
> since they exist in the current working directory in the container.
```

2021-08-27 20:21 UTC, sstevens2 commented on _episodes/06-singularity-images-prep.md
> +> For example, with the `hello-world.sif` image in the current directory on your local system, you could run a container based on this image with:
```suggestion
> For example, with the `hello-world.sif` image in the current directory 
> on your local system, you could run a container based on this image with:
```

2021-08-27 20:23 UTC, sstevens2 commented on _episodes/06-singularity-images-prep.md
> +> You could also take advantage of this option by modifying your alias command shown in the section above to include `-w /home/singularity`.
```suggestion
> You could also take advantage of this option by modifying your alias command 
> shown in the section above to include `-w /home/singularity`.
```

2021-08-27 20:24 UTC, sstevens2 commented on _episodes/06-singularity-images-prep.md
> +> ```
```suggestion
> ~~~
> docker run --rm -it --privileged -v ${PWD}:/home/singularity -w /home/singularity quay.io/singularity/singularity:v3.5.3-slim run -c hello-world.sif
> ~~~
> {: .language-bash}
```

2021-08-27 20:24 UTC, sstevens2 commented on _episodes/06-singularity-images-prep.md
> +> ```
```suggestion
> ~~~
> docker run --rm -it --privileged -v ${PWD}:/home/singularity quay.io/singularity/singularity:v3.5.3-slim run -c /home/singularity/hello-world.sif
> ~~~
> {: .language-bash}
```

2021-08-27 20:26 UTC, sstevens2 requested changes
The codeblocks are using more traditional markdown syntax instead of the lesson codeblock syntax. <- this needs to be fixed before merging

Also broke some lines. <- this is mostly style

2021-08-28 20:21 UTC, jcohen02 commented
Many thanks for the review and suggestions, @sstevens2, and pointing out the use of the wrong syntax for the codeblocks, I didn't notice that when writing the updated content. Suggestions commited.

2021-09-15 16:29 UTC, sstevens2 approved these changes

2024-09-17 10:25 UTC, closed without merging